config/routes.rb
Rails.application.routes.draw do

  resources :offers
  devise_for :users
  root 'static_pages#home'
  get  '/kanban',       to: 'jobs#kanban'
  get  '/promote',      to: 'applications#promote' 
  get  '/unpromote',    to: 'applications#go_back_promote' 
  get  '/reject',       to: 'applications#reject'
  get  '/search_jobs',   to: 'jobs#search_jobs'
  get  '/about',        to: 'static_pages#about'
  get  '/jobs',         to: 'jobs#index'
  get  '/publish',      to: 'jobs#publish'
  get  '/send_offer',   to: 'offers#send_offer'
  get  '/reject_offer', to: 'offers#reject_offer'
  get  '/accept_offer', to: 'offers#accept_offer'
  resources :users
  resources :jobs
  resources :applications
  resources :stages

  resources :comments, only: [:create, :destroy]
  resources :stages, only: [:create, :destroy]
end

app/models/job.rb
class Job < ApplicationRecord
    has_many :applications, class_name: "Application",
                            foreign_key: "job_id",
                            dependent: :destroy
    has_many :users,        through: :applications, source: :user
    has_many :stages,       dependent: :destroy
    has_many :comments,     class_name: "Comment",
                            foreign_key: "job_id",
                            dependent: :destroy
    has_many :users_comment,through: :comments, source: :user

    has_many :offers

    validates :title, presence: true, length: { maximum: 50 }
    validates :description, presence: true

    paginates_per 15

    def apply(user)
        users << user
    end

    def unapply(user)
        users.delete(user)
    end

    def applied?(user)
        users.include?(user)
    end

    def comment(user)
        users_comment << user
    end 

    def next_stage(stage)
        if stage.id == stages.length
            sorted_stages[sorted_stages.index(stage)]
        else  
            sorted_stages[sorted_stages.index(stage)+1]
        end
    end

    def previous_stage(stage)
        if stage.id == 1
            sorted_stages[sorted_stages.index(stage)]
        else  
            sorted_stages[sorted_stages.index(stage)-1]
        end
    end

    def self.unpublished_jobs
        Job.where.not(status: "published")
    end

    def sorted_stages
        Stage.get_sorted_stages(id)
    end

    def status?(symbol)
        status.to_sym == symbol
    end

    def publish
        sorted_stages.map{ |s| s.update_attribute(:order, sorted_stages.index(s))}
        update_attribute(:status, "published")
    end

    def self.find_jobs(job_search)
        Job.where("lower(title) LIKE ? ","%" + job_search + "%")
    end

end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
    before_action :logged_in_user, only: [:show]
    before_action :admin_user, only: [:new, :create, :edit, :destroy, :kanban, :publish]
    before_action :downcase, only: [:search_jobs]

    def new
        @job = Job.new
    end

    def create
        @job = Job.new(job_params)
        @job.save
        redirect_to @job
    end

    def edit

    end

    def show
        @job = Job.find(params[:id])
        @stages = @job.stages   
    end

    def index
        @jobs = Job.page params[:page] 
    end

    def kanban
        @job = Job.find(params[:job_id])
        @stages = @job.sorted_stages
    end

    def publish
        @job = Job.find(params[:job_id])
        @job.publish
        if @job.save 
            flash[:success] = "The job has been published."
        end   
        redirect_to @job
    end

    def search_jobs
        @find_jobs=Job.find_jobs(@search)
    end

    private

        def job_params
            params.require(:job).permit(:title, :description)
        end

        def downcase
            @search = params[:content].downcase
        end
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/jobs/_job.html.erb
<ul class="jobs">
  <% @find_jobs.each do |job| %>
   <div class="card">
  <div class="card-header">
    <%=job.title%>
  </div>
  <div class="card-body">
    <p class="card-text"><%=job.description%></p>
    <%= link_to "Go to work",  job_path(job.id),  class: "btn btn-primary" %>
  </div>
</div>
  <% end %>
</ul>

app/views/jobs/index.html.erb
<% provide(:title, 'All Jobs') %>
<h1>All Jobs</h1>
<% if user_signed_in? %> 
  <% if current_user.admin?%>
  <button type="button" class="btn btn-success">
   <%= link_to 'Create Job', new_job_path %>
  </button>
  <% end %>
  <% end %><br>

<%= form_with url: "/search_jobs", method: :get do |form| %>
  <%= form.text_field :content, placeholder: "Search job..." %>
   <%= form.submit "Search", class: "btn btn-primary" %>
<% end %>
<br>

<%= paginate @jobs, window: 1 %>
<ul class="jobs">
  <% @jobs.each do |job| %>
   <div class="card">
  <h3><div class="card-header">
    <%=job.title%>
  </div></h3>
  <div class="card-body">
    <p class="card-text"><%=job.description%></p>
    <%= link_to "Go to work",  job_path(job.id),  class: "btn btn-primary" %>
  </div>
</div>
  <% end %>
</ul>
<%= paginate @jobs, window: 1 %>

app/views/jobs/kanban.html.erb
<div class="d-sm-flex align-items-center justify-content-between mb-4">
    <h1 class="h3 mb-0 text-gray-800">Kanban for: <%=@job.title%></h1>
</div>

 <div class="row card-group">
    <% @stages.each do |stage| %>
    <div class="col-xl-auto col-md-auto mb-auto">
    <div class="card">
       
      <div class="card-header">
          <h6 class="m-0 font-weight-bold text-primary"><%= stage.name %></h6>
      </div>
      <div class="card-body">
          <% stage.applications.each do |app| %>
                <% if app.active == true %>
                  <div class="card border-left-primary shadow h-100 py-2">
                      <div class="card-body">                              
                          <div class="row no-gutters align-items-center">    
                              <div class="col-auto">
                                  <button type="button" class="btn btn-success btn-circle btn-sm">
                                    <%= link_to ' ', unpromote_path(id: app.id),  class:"fas fa-arrow-left"%> 
                                  </button>
                              </div>
                              <div class="col auto">
                                  &nbsp;<%= link_to app.user.name, user_path(app.user.id)%>  &nbsp;  
                              </div>
                              <div class="col-auto">
                                  <button type="button" class="btn btn-danger btn-circle btn-sm">
                                    <%= link_to ' ', reject_path(id: app.id), data: { confirm: 'Are you sure?' }, class:"fas fa-xmark"%> 
                                  </button>
                                
                                  <button type="button" class="btn btn-info btn-circle btn-sm">
                                    <%= link_to ' ', application_path(app),  class:"fas fa-address-card"%> 
                                  </button>
                                
                                  <button type="button" class="btn btn-success btn-circle btn-sm">
                                    <%= link_to ' ', promote_path(id: app.id),  class:"fas fa-arrow-right"%> 
                                  </button>
                              </div>
                          </div>
                      </div>
                  </div>
                  <br/>
            <% end %>      
          <% end %>
      </div>     
    </div>
    </div>
    <% end%>

     
</div>      



<!--
<div class="kanban" data-id="<%= @job.id %>">
  <% @stages.each do |stage| %>
    <ul class="kanban-col" data-col-id=<%= stage.id %> >
      <li class="kanban-col-name" style="display-block"><%= stage.name %></li>
      <% stage.applications.each do |app| %>
        <% if app.active == true %>
        <li class="kanban-col-item" data-item-id=<%= app.id %> >
          <%= app.user.name %>
          <div class="btn-group-vertical" role="group" aria-label="Vertical button group">
            <button type="button" class="btn btn-danger">
              <%= link_to '', reject_path(id: app.id), data: { confirm: 'Are you sure?' }, class:"glyphicon glyphicon-remove" %> 
            </button>
            <button type="button" class="btn btn-warning">
              <%= link_to '', application_path(app),  class:"glyphicon glyphicon-pencil"%> 
            </button>
            <button type="button" class="btn btn-success">
              <%= link_to '', promote_path(id: app.id),  class:"glyphicon glyphicon-forward"%> 
            </button>
            <button type="button" class="btn btn-success">
              <%= link_to '', unpromote_path(id: app.id),  class:"glyphicon glyphicon-backward"%> 
            </button>
          </div>
        </li>
      <% end %>
      <% end %>
    </ul>
  <% end %>
</div>-->

app/views/jobs/new.html.erb
<% provide(:title, 'New Job') %>
    <div class="card">
        <div class="card-header"><h4>New job</h4>
        <div class="card-body">  
            <%= render 'shared/job_form' %>
            <br/>
            <%# In a future.. with ajax and dinamic forms%>
            <%# <%if current_user.admin? and @job.applications.empty?%>
            <%#    <div class="card" >
            <%#        <div class="card-header">
            <%#            <h4>Do you want to add stages tod the job?</h4>
            <%#        </div>
            <%#        <div class="card-body">
            <%#            <section class="stage_form">
            <%#                <%= render 'shared/stage_form' %>
            <%#           </section>
            <%#        </div>
            <%#    </div>
            <%#<% end %> 
        </div>
    </div>            
</div>

app/views/jobs/search_jobs.html.erb
<% provide(:title, "Search job") %>
<h1>Job search results</h1>

<% if !@find_jobs.nil? %>
 <ul class="jobs">
  <%= render @find_jobs %>
</ul>
<%end%>

app/views/jobs/show.html.erb
<% provide(:title, @job.title) %>
<div class="row">
<div class="card">
  <div class="card-header">
    <%= @job.title %>
  </div>
  <div class="card-body">
    <h5 class="card-title"><%= @job.description %></h5>
    <p class="card-text">
    <% if current_user.admin? %>

    <aside class="col-md-4">
        <section>  
            <% if @job.stages.any? %>
                <div class="card" >
                    <div class="card-header">
                        <h4>Stages of the selection process</h4>
                    </div>
                    <div class="card-body">
                    <ul class="list-group list-group-flush">
                        <% @job.sorted_stages.each do |s| %>
                            <li>
                            <%= link_to s.name, s %> 
                            <% if @job.status?(:created) %>
                            
                            <%= link_to 'Destroy', s, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-danger"%>
                           
                            <% end%>
                            </li>
                        <% end %>
                    </ul>
                    </div>
                </div>
                <br/>
            <% end %>
        </section>
    </aside>
    <% end %>
</div>

<div class="row"> 
<% if user_signed_in? %>   

    <% if current_user.admin? %>
        <%#Manage jobs and applications%> 
        <%= link_to "Manage",  kanban_path(job_id: @job.id),  class: "btn btn-info" %>
        <%#Add stages if dont have%>
         <% if !@job.status?(:published) %>
         <%= link_to "Add stages",  new_stage_path,  class: "btn btn-info" %>
         <%= link_to "Finish job creation", publish_path(job_id: @job.id),  class: "btn btn-info" %>
         <%end%>

    <% else %>
        <%#Could apply%> 
        <%if !current_user.applied?(@job)%>
        <%= form_with(model: current_user.applications.build, local: false) do |f| %>
            <div><%= hidden_field_tag :job_id, @job.id %></div>
            <%= f.submit "Apply now!", class: "btn btn-success" %>
        <% end %>
        <% else %>
            <button type = "button" class= "btn btn-secondary" disabled> You have already applied to this job </button>
        <% end %>
    <% end %>
<%end%>
</div>
</p>
  </div>
</div>
    
    