config/routes.rb
Rails.application.routes.draw do

  resources :offers
  devise_for :users
  root 'static_pages#home'
  get  '/kanban',       to: 'jobs#kanban'
  get  '/promote',      to: 'applications#promote' 
  get  '/unpromote',    to: 'applications#go_back_promote' 
  get  '/reject',       to: 'applications#reject'
  get  '/search_jobs',   to: 'jobs#search_jobs'
  get  '/about',        to: 'static_pages#about'
  get  '/jobs',         to: 'jobs#index'
  get  '/publish',      to: 'jobs#publish'
  get  '/send_offer',   to: 'offers#send_offer'
  get  '/reject_offer', to: 'offers#reject_offer'
  get  '/accept_offer', to: 'offers#accept_offer'
  resources :users
  resources :jobs
  resources :applications
  resources :stages

  resources :comments, only: [:create, :destroy]
  resources :stages, only: [:create, :destroy]
end

app/models/stage.rb
class Stage < ApplicationRecord
  belongs_to :job
  
  has_many :applications

  has_one_attached :challenge_file

  validates :job_id, presence: true
  validates :name, presence: true

  # validates :challenge_file, blob: { content_type: { in: 'application/pdf', message: 'is not a PDF' },
  #                           size: { less_than: 5.megabytes,
  #                                    message: "should be less than 5MB" }

  def equals?(st)
    id == st.id
  end  

  def challenge_path
    ActiveStorage::Blob.service.path_for(challenge_file.key)
  end

  def self.get_sorted_stages(id)
    Stage.where("job_id = ?", id).order(:created_at)
  end

end

app/controllers/stages_controller.rb
class StagesController < ApplicationController
  before_action :set_stage, only: %i[ show edit update destroy ]
  before_action :admin_user

  # GET /stages or /stages.json
  def index
    @stages = Stage.all
  end

  # GET /stages/1 or /stages/1.json
  def show
  end

  # GET /stages/new
  def new
    @stage = Stage.new
  end

  # GET /stages/1/edit
  def edit
  end

  # POST /stages or /stages.json
  def create
    @stage = Stage.new(stage_params)
    @stage.challenge_file.attach(stage_params[:challenge_file])

    respond_to do |format|
      if @stage.save
        format.html { redirect_to job_path(params["stage"][:job_id]), notice: "Stage was successfully created." }
        format.json { render :show, status: :created, location: @stage }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @stage.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stages/1 or /stages/1.json
  def update
    respond_to do |format|
      @stage.challenge_file.attach(stage_params[:challenge_file])
      if @stage.update(stage_params)
        format.html { redirect_to stage_url(@stage), notice: "Stage was successfully updated." }
        format.json { render :show, status: :ok, location: @stage }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @stage.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stages/1 or /stages/1.json
  def destroy
    @job_id =  @stage.job.id
    @stage.destroy

    respond_to do |format|
      format.html { redirect_to job_path(@job_id), notice: "Stage was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_stage
      @stage = Stage.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def stage_params
      params.require(:stage).permit(:name, :job_id, :challenge_file)
    end
end

app/helpers/stages_helper.rb
module StagesHelper
end

app/views/stages/_form.html.erb
<%= form_with(model: stage) do |form| %>
  <% if stage.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(stage.errors.count, "error") %> prohibited this stage from being saved:</h2>

      <ul>
        <% stage.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :job_id %>
    <%= form.select :job_id, options_for_select(Job.unpublished_jobs.map{ |j| [j.title,j.id]}) %>
  </div>

  <span class="pdf">
      <%= form.label :challenge_file,  "Upload a challenge file: "%>
      <%= form.file_field :challenge_file, accept: "application/pdf" %>
  </span>
  <br/>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/stages/edit.html.erb
<h1>Editing Stage</h1>

<%= form_with(model: @stage) do |form| %>
  <% if @stage.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@stage.errors.count, "error") %> prohibited this stage from being saved:</h2>

      <ul>
        <% @stage.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <span class="pdf">
      <%= form.label :challenge_file,  "Upload a challenge file: "%>
      <%= form.file_field :challenge_file, accept: "application/pdf" %>
  </span>
  <br/>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>



<%= link_to 'Show', @stage %> |
<%= link_to 'Back', stages_path %>

app/views/stages/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Stages</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Job</th>
      <th>File</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @stages.each do |stage| %>
      <tr>
        <td><%= stage.name %></td>
        <td><%= stage.job_id %></td>
        <td><%= stage.challenge_file %></td>
        <td><%= link_to 'Show', stage %></td>
        <td><%= link_to 'Edit', edit_stage_path(stage) %></td>
        <td><%= link_to 'Destroy', stage, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Stage', new_stage_path %>

app/views/stages/new.html.erb
<h1>New Stage</h1>

<%= render 'form', stage: @stage %>

<%= link_to 'Back', stages_path %>

app/views/stages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @stage.name %>
</p>

<p>
  <strong>Job:</strong>
  <%= @stage.job_id %>
</p>

<%= link_to 'Edit', edit_stage_path(@stage) %> |
<%= link_to 'Back', stages_path %>