config/routes.rb
Rails.application.routes.draw do

  resources :offers
  devise_for :users
  root 'static_pages#home'
  get  '/kanban',       to: 'jobs#kanban'
  get  '/promote',      to: 'applications#promote' 
  get  '/unpromote',    to: 'applications#go_back_promote' 
  get  '/reject',       to: 'applications#reject'
  get  '/search_jobs',   to: 'jobs#search_jobs'
  get  '/about',        to: 'static_pages#about'
  get  '/jobs',         to: 'jobs#index'
  get  '/publish',      to: 'jobs#publish'
  get  '/send_offer',   to: 'offers#send_offer'
  get  '/reject_offer', to: 'offers#reject_offer'
  get  '/accept_offer', to: 'offers#accept_offer'
  resources :users
  resources :jobs
  resources :applications
  resources :stages

  resources :comments, only: [:create, :destroy]
  resources :stages, only: [:create, :destroy]
end

app/models/offer.rb
class Offer < ApplicationRecord
  belongs_to :user
  belongs_to :job

  def status?(symbol)
    status.to_sym == symbol
  end

  def reject
    update_attribute(:status, "rejected")
  end

  def accept
    update_attribute(:status, "accepted")
  end
end

app/controllers/offers_controller.rb
class OffersController < ApplicationController
  before_action :set_offer, only: %i[ show edit update destroy send_offer]
  before_action :logged_in_user, only: [:show, :index]
  before_action :admin_user, only: [ :new, :create, :edit, :destroy, :send_offer]

  # GET /offers or /offers.json
  def index
    @offers = Offer.all
  end

  # GET /offers/1 or /offers/1.json
  def show
  end

  # GET /offers/new
  def new
    @offer = Offer.new
  end

  # GET /offers/1/edit
  def edit
  end

  # POST /offers or /offers.json
  def create
    @offer = Offer.new(offer_params)

    respond_to do |format|
      if @offer.save
        format.html { redirect_to offer_url(@offer), notice: "Offer was successfully created." }
        format.json { render :show, status: :created, location: @offer }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @offer.errors, status: :unprocessable_entity }
      end
    end
  end

  def send_offer
    @offer.status = :sent
    if @offer.update(offer_params)
      UserMailer.send_offer(@offer.user, @offer).deliver_now
      flash[:info] = "Offer was sended to the candidate."
      redirect_to offer_url(@offer)
    else
      redirect_to edit_offer_url(@offer)
    end
  end

  # PATCH/PUT /offers/1 or /offers/1.json
  def update
    respond_to do |format|
      if @offer.update(offer_params)
        format.html { redirect_to offer_url(@offer), notice: "Offer was successfully updated." }
        format.json { render :show, status: :ok, location: @offer }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @offer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /offers/1 or /offers/1.json
  def destroy
    @offer.destroy

    respond_to do |format|
      format.html { redirect_to offers_url, notice: "Offer was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def reject_offer
    @offer = Offer.find(params[:id])
    if @offer.status?(:sent)
      @offer.reject
      if @offer.save
        flash[:danger] = "You have rejected the offer."
        redirect_to offer_url(@offer)
      end
    else
      flash[:danger] = "You don't have an offer."
      redirect_to root_url
    end
  end

  def accept_offer
    @offer = Offer.find(params[:id])
    if @offer.status?(:sent)
      @offer.accept
      if @offer.save
        flash[:success] = "You have accepted the offer."
        redirect_to offer_url(@offer)
      end
    else
      flash[:danger] = "You don't have an offer."
      redirect_to root_url
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_offer
      @offer = Offer.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def offer_params
      params.require(:offer).permit(:content, :user_id, :job_id, :status)
    end
end

app/helpers/offers_helper.rb
module OffersHelper
end

app/views/offers/_form.html.erb
<%= form_with(model: offer) do |form| %>
  <% if offer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(offer.errors.count, "error") %> prohibited this offer from being saved:</h2>

      <ul>
        <% offer.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>
<!--
  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id %>
  </div>

  <div class="field">
    <%= form.label :job_id %>
    <%= form.text_field :job_id %>
  </div>

  <div class="field">
    <%= form.label :status %>
    <%= form.check_box :status %>
  </div> %>
-->
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/offers/edit.html.erb
<h1>Editing Offer</h1>

<%= form_with(model: @offer, url: send_offer_path(@offer), method: "get") do |form| %>
  <% if @offer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@offer.errors.count, "error") %> prohibited this offer from being saved:</h2>

      <ul>
        <% @offer.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <%= hidden_field_tag :id, @offer.id %>
  
  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>
<!--
  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id %>
  </div>
  <div class="field">
    <%= form.label :job_id %>
    <%= form.text_field :job_id %>
  </div>
  <div class="field">
    <%= form.label :status %>
    <%= form.check_box :status %>
  </div> %>
-->
  <% if @offer.status?(:created) %>      
    <div class="actions">
        <%= form.button "Send Offer", data: { confirm: "Are you sure?" } %>
    </div>
  <% end %>
<% end %>

app/views/offers/index.html.erb
<h1>Offers</h1>
<%if current_user.admin?%>
<table>
  <thead>
    <tr>
      <th>Content</th>
      <th>Candidate</th>
      <th>Job</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @offers.each do |offer| %>
      <tr>
        <td><%= offer.content %></td>
        <td><%= offer.user.name %></td>
        <td><%= offer.job.title %></td>
        <td><%= offer.status %></td>
        <td><%= link_to 'Show', offer %></td>
        <td><%= link_to 'Edit', edit_offer_path(offer) %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%else%>
<table>
  <thead>
    <tr>
      <th>Job</th>
      <th>Status</th>
    </tr>
  </thead>

  <tbody>
    <% @current_user.offers.each do |offer| %>
      <tr>
        <td><%= link_to offer.job.title, offer_path(offer) %></td>
        
        <td><%= offer.status %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%end%>

app/views/offers/new.html.erb
<h1>New Offer</h1>

<%= render 'form', offer: @offer %>

<%= link_to 'Back', offers_path %>

app/views/offers/show.html.erb
<h1>Offer details</h1>

<%if !current_user.admin?%>
  <p>
    <strong>Cogratulations, you have an offer for: </strong>
    <%= @offer.job.title %>
  </p>

  <p>
    <strong>Details:</strong>
    <%= @offer.content %>
  </p>


  <p>
    <strong>Status:</strong>
    <%= @offer.status %>
  </p>

  <% if @offer.status?(:sent) %>          
      <div class="actions">
          <%= link_to 'Reject', reject_offer_path(id: @offer.id), data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %> 
          <%= link_to 'Accept', accept_offer_path(id: @offer.id), data: { confirm: 'Are you sure?' }, class: "btn btn-success" %> 
      </div>
  <% end %>
<% else %>
 <p>
    <strong>You have sent an offer for: </strong>
    <%= @offer.job.title %>
  </p>

   <p>
    <strong>To: </strong>
    <%= @offer.user.name%>
  </p>

  <p>
    <strong>Details:</strong>
    <%= @offer.content %>
  </p>

<% end %>